### ISSUE TITLE
Movies data limit stuck at 50

### ISSUE THREAD

**Issue by abusayed0206** [timciep/letterboxd-diary-embed#2]
I recently found this repo deployed on Cloudflare. I changed the limit for movie data, but only 50 movies are shown.

Worker: lb.sayed.page
Used here: film.sayed.page

Please have a look.

**Comment by timciep** [comment]
The data comes from Letterboxd profile RSS feed, so the results will be limited to what's included in that.

Closing, as this is not an issue for this project.
